//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnn.Modules.SecurityCenter.Services
{
    using DotNetNuke.Common.Utilities;
    using DotNetNuke.Services.Localization;
    using Dnn.Modules.SecurityCenter.ViewModels;
    using System.Diagnostics.CodeAnalysis;
    using System.Web.Hosting;
    using System.Threading;
    using static Dnn.Modules.SecurityCenter.ViewModels.LocalizationViewModel;

    /// <summary>
    /// Provides strongly typed localization services for this module.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class LocalizationService : ILocalizationService
    {
        private readonly ILocalizationProvider localizationProvider;
        private readonly LocalizationViewModel viewModel;
        private readonly string cacheKey;
        private string resourceFileRoot;

        private string ResourceFileRoot
        {
            get
            {
                if (string.IsNullOrWhiteSpace(this.resourceFileRoot))
                {
                    this.resourceFileRoot = HostingEnvironment.MapPath(
                        "~/DesktopModules/Dnn.SecurityCenter/resources/App_LocalResources/");
                }

                return this.resourceFileRoot;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationService"/> class.
        /// </summary>
        public LocalizationService()
        {
            this.localizationProvider = new LocalizationProvider();
            this.cacheKey = "Dnn.Modules.SecurityCenter" + "_Localization_" + Thread.CurrentThread.CurrentCulture;
            this.viewModel = new LocalizationViewModel();
            var viewModel = DataCache.GetCache<LocalizationViewModel>(this.cacheKey);
            if (viewModel is null)
            {
                viewModel = this.HydrateViewModel();
                DataCache.SetCache(this.cacheKey, viewModel);
            }
            this.viewModel = viewModel;
        }

        /// <summary>
        /// A viewmodel that strongly types all resource keys.
        /// </summary>
        public LocalizationViewModel ViewModel
        {
            get
            {
                return this.viewModel;
            }
        }

        private string GetString(string key, string file)
        {
            return this.localizationProvider.GetString(key, this.ResourceFileRoot + file);
        }

        private LocalizationViewModel HydrateViewModel()
        {
            var modelvalidation = new ModelValidationInfo
            {
                IdGreaterThanZero = this.GetString("IdGreaterThanZero", "ModelValidation.resx"),
                NameRequired = this.GetString("NameRequired", "ModelValidation.resx"),

            };
            viewModel.ModelValidation = modelvalidation;
            var ui = new UIInfo
            {
                DnnPlatformVersion = this.GetString("DnnPlatformVersion", "UI.resx"),
                DnnSecurityCenter = this.GetString("DnnSecurityCenter", "UI.resx"),
                Loading = this.GetString("Loading", "UI.resx"),
                NoBulletins = this.GetString("NoBulletins", "UI.resx"),

            };
            viewModel.UI = ui;
            return viewModel;

        }
    }
}

